/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

// source: mtmanapi.i

#ifndef SWIG_mtmanapi_WRAP_H_
#define SWIG_mtmanapi_WRAP_H_

class Swig_memory;

#endif
